name: Go

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: "test (age ${{ matrix.age_version }}, opentofu ${{ matrix.opentofu_version }})"
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        include:
          # nixos-25.11
          - age_version: "1.3.1"
            opentofu_version: "1.10.9"

          # nixpkgs-unstable
          - age_version: "1.3.1"
            opentofu_version: "1.11.5"

    env:
      AGE_VERSION: ${{ matrix.age_version }}
      TOFU_VERSION: ${{ matrix.opentofu_version }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install age
        run: |
          set -o xtrace
          curl --location https://github.com/FiloSottile/age/releases/download/v${AGE_VERSION}/age-v${AGE_VERSION}-linux-amd64.tar.gz --output age.tar.gz
          tar -xzf age.tar.gz
          chmod +x age/age
          sudo mv age/age /usr/bin/age

      - name: Install tofu
        run: |
          set -o xtrace
          curl --location https://github.com/opentofu/opentofu/releases/download/v${TOFU_VERSION}/tofu_${TOFU_VERSION}_linux_amd64.tar.gz --output tofu.tar.gz
          tar -xzf tofu.tar.gz
          chmod +x tofu
          sudo mv tofu /usr/bin/tofu

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: "1.25.5"

      - name: Build
        run: |
          go build

      - name: Test
        run: |
          go test
